apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site7
  namespace: default
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-site7
  template:
    metadata:
      labels:
        app: nginx-site7
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
