apiVersion: batch/v1
kind: Job
metadata:
  name: presync-hook-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: logger
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["echo 'PreSync hook: starting deployment process...'"]
      restartPolicy: Never
  backoffLimit: 1
